### ISSUE TITLE
Mod reduces rent value of many homes to $10/month

### ISSUE THREAD

**Issue by shssoichiro** [Jimmyokok/LandValueOverhaul#1]
After installing and activating this mod in my city, and letting the city run for some time, I am seeing that many homes are updating their rent values to $10/month, which is of course unrealistically low. This is occurring in both high and low land value areas of the city (according to the land value overlay).

**Comment by Jimmyokok** [comment]
- If you are not using the ExtendedTooltips mod to monitor rent values: the rent values the game shows you is **per-area** monthly rent. 

- _Reason behind your observation:_ The land value is computed and updated according to **the maximum rent these families are willing to pay**, which is affected by their daily income and other city-service-related factors. The mod did not alter how these affect the willing-to-pay rent, but altered the land value update mechanism so that **it favors those families/renters that are less willing to pay the rent**. To put this in another way, **the land value will stablize at a level where most less wealthy families on the road edge are willing to pay the rent, and getting low land values means your homes are far from wealthy to pay them**. In the original game, the land value will continue to rise way above these families could afford, driving them out of your city. However, this process is hardly noticeable, so you are not aware that this constantly happens.

- _Why realistic rent is not possible?_ In the original game, you will see these homes paying maybe >$100 rent/month(which seems a realistic value for low density residentials). But the high rent warnings will soon appear, indicating that >70% families/renters don't want to pay the rent. The result will be either these families move away and get replaced by new families moving in (which is hardly observable), or the buildings are slowly abandoned. **The thing is, in-game citizens are actually not earning realistic wages (> $1000/month for highly-educated) so that they want to pay realistic rent.** So if you want realistic rent values without driving citizens away from your city, the game's wage system should also get an overhaul.

**Comment by shssoichiro** [comment]
Thanks for the info. I am using ExtendedTooltips, but the rest of the explanation makes sense.
