### ISSUE TITLE
please add to the Paradox Mods

### ISSUE THREAD

**Issue by shayanz23** [Jimmyokok/LandValueOverhaul#12]
I know the update has rewritten to "fix" the land value. But compared to  your mod it's really bad. The same issue as before has instantly come back and it's so annoying.

**Comment by Jimmyokok** [comment]
So, the new land value system is still causing trouble? (I'm still waiting for ExtendedRoadUpgrades to experience the new game version)
Please describe the problems you met as detailedly as possible. I'will consider a mod update according to the precious feedbacks from you and other 1.1.0 players.

**Comment by ChristopherJohnBrennan** [comment]
The biggest issue that I'm seeing in 1.1.0 is that demand for low density residential drops away very, very quickly.  There's some demand at the beginning, but in the attached screenshot I've just hit level 1 with 98 people and already there's only demand for medium density.  I've already seen one house with the rent too high message.

I haven't seen the death spiral problem but I don't know if that's just because haven't gotten far enough to see it. 

I loved your mod and would be thrilled if you could take a shot at it again for 1.1.0.

![Screenshot 2024-03-30 032031](https://github.com/Jimmyokok/LandValueOverhaul/assets/8902659/203f4f18-6179-4007-9e25-df32c98b68f4)

**Comment by shayanz23** [comment]
Sorry for taking so long to respond,  I find that the problems I have are high rent for single family residences, even if they are wealthy. The land value isn't even that high to me tbh, it has gone up a lot, but that's because it was almost 0 when I had the mod, but I don't know exactly what it was. 
Land Value map on new update without the mod:
![20240328_18h44m26s_grim](https://github.com/Jimmyokok/LandValueOverhaul/assets/35084589/65f9fa87-408f-431a-852c-365ced4a1168)

And I also find that residential demand is almost 0 for low, medium, and high density, even though there are very few unemployed. I'm not sure if that related to this though.

**Comment by Jimmyokok** [comment]
> The biggest issue that I'm seeing in 1.1.0 is that demand for low density residential drops away very, very quickly. There's some demand at the beginning, but in the attached screenshot I've just hit level 1 with 98 people and already there's only demand for medium density. I've already seen one house with the rent too high message.
> 
> I haven't seen the death spiral problem but I don't know if that's just because haven't gotten far enough to see it.
> 
> I loved your mod and would be thrilled if you could take a shot at it again for 1.1.0.
> 
> ![Screenshot 2024-03-30 032031](https://private-user-images.githubusercontent.com/8902659/318176411-203f4f18-6179-4007-9e25-df32c98b68f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTIxMzYsIm5iZiI6MTcxMTc5MTgzNiwicGF0aCI6Ii84OTAyNjU5LzMxODE3NjQxMS0yMDNmNGYxOC02MTc5LTQwMDctOWUyNS1kZjMyYzk4YjY4ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMDk0MzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmMmQ4YzVmNzA0YWRjZTU2NGQwYTQyYmFkOWE0NjE3Yzg0M2Q1MjRhMDc5YjU2MzA4MmIxNDZmZDg2OTQ4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SCqbtCvBaVLV5jNcwo7tx9Pw4LxqrHSjzE73nN2jMhk)

The game's code tells us that the residential demand is almost determined by the proportion of empty residential properties in your city. It's very unlikely to be a land value issue, unless the update 1.1.0 has modified how residentials zones pop up.

**Comment by Jimmyokok** [comment]
> Sorry for taking so long to respond, I find that the problems I have are high rent for single family residences, even if they are wealthy. The land value isn't even that high to me tbh, it has gone up a lot, but that's because it was almost 0 when I had the mod, but I don't know exactly what it was though, I just remember the land value view being almost completely white, unlike the current one. Land Value map on new update without the mod: ![20240328_18h44m26s_grim](https://private-user-images.githubusercontent.com/35084589/318183794-65f9fa87-408f-431a-852c-365ced4a1168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTIxMzYsIm5iZiI6MTcxMTc5MTgzNiwicGF0aCI6Ii8zNTA4NDU4OS8zMTgxODM3OTQtNjVmOWZhODctNDA4Zi00MzFhLTg1MmMtMzY1Y2VkNGExMTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA5NDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MjE3NWY4YjdjYjVjMWJhYmY1OGRlMGQzNGRkMmE3MTgzMTU5ZmRjNzI5NDQxNWFlZTlhM2UxOTRjMzFkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R91QTAtAXOReRBCH_Ftq04_3CDkHjJkHjPm6nCi1Bqw)
> 
> And I also find that residential demand is almost 0 for low, medium, and high density, even though there are very few unemployed. I'm not sure if that related to this though.

Very informative. One thing for sure is that the high rent issue for low density residentials is not even touched by the newest game update. My mod treats low density residentials specially by counting their area sizes to be constantly 1x1, which resulting in ultra low land value below them. The high rent could drive many residents out of your city and leave your city a whole forest of empty properties, which is why your residential demand is unusually low.

Now, the low density fix will return, but I'm still not sure about the core land value mechanism, since I haven't yet seen anything about how the new land value system works in a medium/large city.
