### ISSUE TITLE
In a new save, creating low-density houses causes a massive, endless line of trucks.

### ISSUE THREAD

**Issue by buenofarray** [Jimmyokok/LandValueOverhaul#3]
Tested on 1.19, simply start a new save, and zone some low density houses. Massive endless trucks of queues form, lasting for minutes. 

This behaviour was observed running the game, BepinExPack, and this mod, just on their own, no other mods installed.

![image](https://github.com/Jimmyokok/LandValueOverhaul/assets/32202821/ece5e69f-16b9-4174-99f8-62aaaab0b5ee)

**Comment by Jimmyokok** [comment]
It is an observed bug in 1.0.18f1. However, only a very tiny proportion of players is facing this issue and I myself have never encountered it throughout many new saves. I suspect it's caused by a divide-by-zero operation and I will fix it in the next mod update (the 1.0.19f1 compatibility patch, should be worked on tomorrow).

Could you provide your game save, so I can repeat this behavior and search for its root cause?

**Comment by buenofarray** [comment]
Sorry for the late reply. I had a busy weekend.

I have updated to the more recent version of your mod, and the issue still happens. The issue happens with and without mods, but I'm going to share a list of my installed mods, just in case that helps locate the culprit, in case there's some odd conflict or something.

![image](https://github.com/Jimmyokok/LandValueOverhaul/assets/32202821/c8067022-5bf7-49e0-8612-079508f44b0f)

I've uploaded both saves (before building and after building) to Drive: 

https://drive.google.com/drive/folders/1sgLhHKDZEHapVGMtfxc3IDRqx-hCfaLc?usp=sharing

**Comment by Jimmyokok** [comment]
Thanks for your detailed information and save files shared!
Some players in the chinese cities2 community believe it to be a vanilla bug. I will try to find its cause, giving the save files you shared, but don't expect a solid conclusion.

**Comment by Jimmyokok** [comment]
I have located the problem. It turns out to be **yeeeeeeeeeet another** numerically unstable piece of code from vanilla, resulting in the frequency of material upkeep delivery being inversely proportional to the absolute value of the building upkeep.
I small update (1.4.3) has been made to fix this vanilla flaw.

**Comment by buenofarray** [comment]
> I have located the problem. It turns out to be **yeeeeeeeeeet another** numerically unstable piece of code from vanilla, resulting in the frequency of material upkeep delivery being inversely proportional to the absolute value of the building upkeep. I small update (1.4.3) has been made to fix this vanilla flaw.

Mate you're doing god's work. I haven't tested it yet, but I saw the duplicate confirming the fix. I can finally play again!!
