### ISSUE TITLE
Wealth

### ISSUE THREAD

**Issue by Thelic38** [Jimmyokok/LandValueOverhaul#5]
First off, thank you for this mod. It alone is making the game playable at this stage. Some of these comments won't necessarily pertain directly to this mod, but it might be some nice data points for you.

I've been testing this mod in my city as well as a few other balance mods for several real days running at 4x speed with no new building to see what it looks like as a steady state.

-Realistic Density
-Traffic Reduction Remover
-Population Rebalance

City size ~38,000 Residents @ 13% taxes. I found that taxing lower only resulted in a higher homeless population.

Things to note:

-The game is extremely sensitive to demolishing residential buildings. It seems to spawn new families faster then the displaced ones can find a home, especially true at lower tax rates. This results in a jump of homeless rates, followed by crime.

-Wealth in general climbs to extraordinarily high values over time. Like really high. I would say this is likely due to this mod, with lower rent people/businesses are generating extra money and they just don't spend it. Maybe a luxury tax or something would keep this in check? It would be nice if we could tax the wealthy, not the highly educated.

![image](https://github.com/Jimmyokok/LandValueOverhaul/assets/152677602/de6fed8b-b104-45d8-8c30-89fe12e5d9b5)

-Every building hits L5. This is a side effect of this mod. You can't really create lower level/wealth portions of the city.

-The tax income is extreme, if you leave it at 10% you're rolling in money within the first 30 minutes, and it just keeps going. If you lower it to try and make the game harder you start getting the homeless problem, A city of 5,000 shouldn't be able to afford a Hospital, Police HQ, University, Disease Control Center, etc...I think this is a result of this mod (though the base game is also too easy IMO), as the income in general is higher with low land values, leading to increased tax revenue.

-Some (Most) of the signature buildings still cannot keep the same business. Not sure why, but I have 2 of the low density office signature buildings a block apart, one will cycle tenants regularly, the other has the same one it started with.

-There are so many dogs. Households with 5+ dogs are not uncommon. I've seen as high as 12. Want to know where your framerate is going??? I like dogs, but they add little/nothing to the simulation. Do people get more dogs with wealth?

![image](https://github.com/Jimmyokok/LandValueOverhaul/assets/152677602/28c90392-3c31-44f7-986b-e57ff9b8a142)

Come on lady, leave some sidewalk for the rest of us.

In general there seems to be a lack of a system to keep things trending towards the middle. Without mods the game spirals into a high land value situation that kills the city. With the mods the city is overly healthy to the point its boring and unchallenging.

**Comment by Thelic38** [comment]
Newest version of Population Rebalance seems to have fixed most of the homeless issue.

**Comment by chbaker0** [comment]
> -Wealth in general climbs to extraordinarily high values over time. Like really high. I would say this is likely due to this mod, with lower rent people/businesses are generating extra money and they just don't spend it. Maybe a luxury tax or something would keep this in check? It would be nice if we could tax the wealthy, not the highly educated.

While this does kind of break the game, it is also what would happen in real life: normally, this wealth accumulates in the form of property values, for the landowners. If land values are kept 'artificially' low, and renters make the same income but pay less rent as a result, then their wealth will climb.

I think fundamentally the problem is how the base game models landowners and rent. For example, why do single family home residents pay rent? Yes, some people do in real life but many more own their homes. Yes, as property values go up so will their wealth but this wealth will not be easily accessible (they would need to find a buyer and move somewhere cheaper).

If the game supported the idea of buying property (including apartments!) many issues would go away: rising land values would still negatively affect renters, but it would have a mostly positive effect on owners. They would have the option to sell and move instead of paying more and more rent.

Also in the game the rent money essentially disappears (right?). Of course in real life this doesn't happen, and it's probably why artificially low rents break the game so much. Instead of the money just being spent into the same market by a different person, it inflates the money supply. I think that's why I see excessive commercial demand when I'm playing with this mod. I doubt the base game makes an effort to model inflation.

**Comment by Thelic38** [comment]
I don't have a good answer for this, I imagine no one does because these are stating to sound an awful like real world problems.

What this mod did is removed a large portion of a hard money sink from the economy (all people need housing). What we need now is some softer money sinks to keep the balance in check. Maybe happiness should be tied not only to wealth but also how much disposable income they are using. If we have excess wealth we shop more, therefore are happier.

I'd be curious to know how money is handled with splitting and death of a household. Do new adults from a wealthy family leave with a big chunk of the cash reserves when they move out? Where does the money go when the last member of a household dies?

Do wealthy households consume more when they shop?

**Comment by Jimmyokok** [comment]
- The first point is very true. Demolishing residential areas will instantly create a large homeless population, and when new homes are built, they have to compete with new residents in finding new homes. Looking into the game code, lower tax rate actually encourages more people to move into the city. This is probably why lower tax rate results in a higher homeless population.
- This mod indeed makes almost all residents extraordinarily rich. That's not something that should be handled by this mod, as the root cause is that rich residents don't spend most of their excess income after paying the rent, but just endlessly accumulate them.
- The tax income issue is weird. In game, the tax simply and directly takes effect on absolute income (before spending any money on anything). For residents, the income is **fixed** to these values:
  - Uneducated: 1200
  - Poorly educated: 2000
  - Educated: 2500
  - Well educated: 3500
  - Highly educated: 5000
 That means, residential tax should be quite stable. Given your extremely high tax income, it should be caused by extremely high commercial/industrial/office income, as a result of everybody having enough money to shop.
- Some signature buildings just can't make enough money. They constantly go backrupt and the best solution to this could be to avoid building these typical signature buildings.
- The pet mechanism is alien to me. I haven't looked into this part of the game code, so I can't help you with this problem. I suppose this is yet another numerically unstable system made by the game developer.
- Household never splits, and there are literally no inflation mechanism in this game (from the game code). While I agree with you that residents with excess wealth should shop more, this would definitely raise the commercial income, then the industrial and the office income, and your tax income at last.
