### ISSUE TITLE
Buildings level up too fast

### ISSUE THREAD

**Issue by LDTips** [Jimmyokok/LandValueOverhaul#7]
I just started a new game with the mod and noticed the industrial and commercial buildings are upgrading quickly to level 3+. Most of the commerical are at lvl 3, and some of the industrial are at lever 4 even. This results in "not enough employees" issue. I assume this gets fixed later in the game when population rises, but is it a concern in the early game if something like this happens?

**Comment by Jimmyokok** [comment]
It won't damage your city, but it indeed somehow affects your gameplay. 
I have received many similar feedbacks. Non-residential buildings are just making too much money and therefore paying more rent than residential buildings, but their upgrade cost is even less than residentials. This is a vanilla feature but of cource it doesn't make sense. Raising the building upgrade cost for non-residential properties is already on schedule but will not be included in any small updates because it affects existing save games.
